---
- name: Deploy Docker image and Kubernetes resources for Anime Frontend
  hosts: localhost
  remote_user: hari
  tasks:
    - name: Deploy Docker image and Kubernetes resources
      become: false
      shell: kubectl apply -f "{{ item }}"
      with_fileglob:
        - ../kubernetes/*.yaml
