apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: animelocal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anime-service
                port:
                  number: 9292